---
namespace: directus

stack:
  defines: process-group

  metadata:
    name: Directus
    icon: https://pbs.twimg.com/profile_images/1495544699410653190/Vb675Xa3_400x400.jpg
    description: |
      Directus is the world's first Open Data Platform for instantly turning any SQL database into an API and beautiful no-code app.
      Default username/password: admin@directus.io / directus
    website: https://directus.io/
    github: https://github.com/directus/directus

  runnable-list:
    - directus/database
    - directus/cache
    - directus/server
